# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.4'

services:
  # laundra:
  #   image: laundra
  #   build:
  #     context: .
  #     dockerfile: ./Dockerfile
  #   ports:
  #     - 5123:5123
  #   depends_on:
  #     - db

  db:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    ports:
      - "1433:1433"
    environment:
        SA_PASSWORD: "S3cur3P@ssW0rd!"
        ACCEPT_EULA: "Y"